module.exports = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  PAGE_NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER: 500,
  NOT_ACCEPTABLE: 406,
  DATA_CONFLICT: 409,
  UNAUTHENTICATED: 401,
  CREATED: 201,
  FAIL: 400,
  ACTIVE: "1",
  INACTIVE: "0",
  DELETE: "2",
  PER_PAGE: 10,
  DEFAULT_PAGE: 1,
  MIN_AGE: 18,
  VERIFIED: "1",
  S3_ENABLE: "true",
  NOT_VERIFIED: "0",
  BALANCE: 0,
  MAIL_SUBJECT_MESSAGE_REGISTRATION:
    "Welcome to Our Platform - Registration Successful",
  MAIL_SUBJECT_MESSAGE_RESEND_OTP: "New OTP for verification",
  MAIL_SUBJECT_FORGET_PASSWORD: "Password Reset Request",
  VERIFY_EMAIL: "Verify your email.",
  TRANSACTION_TYPE: {
    DEPOSIT: "deposit",
    WITHDRAWL: "withdrawl",
  },
  ACCOUNT_TYPE: {
    SAVING: "saving",
    CURRENT: "current",
  },
  BANK: {
    ACTIVE: "1",
    INACTIVE: "0",
  },
  BET_ALLOW: {
    ALLOW: true,
    DISALLOW: false,
  },
  QUESTION: "question",
  DEPOSIT: "deposit",
  BANK_SLIDER: "bank_slider",
  GAME: [
    {
      name: "head_tail",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "rock_paper_scissors",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "spin_wheel",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "number_guess",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "dice_rolling",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "card_finding",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "number_slot",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "number_pool",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
    {
      name: "keno",
      min: 1,
      max: 100,
      odd: {
        match1: 10,
        match2: 20,
        match3: 30,
        match4: 40,
        match5: 50,
        match6: 60,
        match7: 70,
      },
      probability: 1,
      delete: "dt",
    },
    { name: "ludo", min: 1, max: 100, odd: 150, probability: 1, delete: "dt" },
    {
      name: "black_jack",
      min: 1,
      max: 100,
      odd: 150,
      probability: 1,
      delete: "dt",
    },
  ],
};
